apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: worker-deployment
  name: worker-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: worker-deployment
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: worker-deployment
    spec:
      containers:
      - image: schoolofdevops/worker:latest
        name: worker-deployment
        resources: {}
