apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: vote
    tier: front
  name: vote
spec:
  replicas: 3
  template:
    spec:
      containers:
      - image: lfarizav/vote
        name: vote
        envFrom:
          - configMapRef: 
              name: vote-options
              optional: true
