apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../base
patchesStrategicMerge:
- deployment.yaml
- svc.yaml
commonAnnotations:
  supported-by: Luis Felipe Ariza Vesga
configMapGenerator:
  - name: vote-options
    envs: 
      - options.env
images:
   - name: schoolofdevops/vote
     newTag: v4 # {"$imagepolicy": "flux-system:vote:tag"}
