---
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: GitRepository
metadata:
  name: instavote
  namespace: instavote
spec:
  interval: 30s
  ref:
    branch: main
  secretRef:
    name: github-credentials
  url: https://github.com/lfarizav/instavote-deploy.git
