---
apiVersion: notification.toolkit.fluxcd.io/v1beta3
kind: Alert
metadata:
  labels:
    kustomize.toolkit.fluxcd.io/name: instavote
    kustomize.toolkit.fluxcd.io/namespace: instavote
  name: slack-notif
  namespace: instavote
spec:
  eventSeverity: info
  eventSources:
  - kind: Kustomization
    name: '*'
  - kind: GitRepository
    name: '*'
  - kind: HelmRelease
    name: '*'
  providerRef:
    name: slack
