---
apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImageRepository
metadata:
  name: vote
  namespace: instavote
spec:
  exclusionList:
  - ^.*\.sig$
  image: lfarizav/vote
  interval: 10m0s
  provider: generic
