---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: vote-staging
  namespace: flux-system
spec:
  interval: 1h
  path: ./kustomize/vote/staging
  prune: true
  sourceRef:
    kind: GitRepository
    name: instavote-deploy
  targetNamespace: instavote-deploy
  timeout: 2m0s
