---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: worker-staging
  namespace: flux-system
spec:
  interval: 1h
  path: ./kustomize/worker/staging
  prune: true
  sourceRef:
    kind: GitRepository
    name: instavote-deploy
  targetNamespace: instavote-deploy
