apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: vote
    tier: front
  name: vote
spec:
  replicas: 4
  selector:
    matchLabels:
      app: vote
  strategy: {}
  template:
    metadata:
#      annotations:
#        k8s.v1.cni.cncf.io/networks: |
#          [{
#            "name": "bridge-net"
#          }]
      labels:
        app: vote
        tier: front
    spec:
      containers:
      - image: schoolofdevops/vote:v4
        name: vote
        resources: {}
